import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
import ts from 'typescript';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'scene-auth-'));
const source=await fs.readFile('lib/cloud.ts','utf8');
let code=ts.transpile(source,{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}).replace("import { validate } from './manuscript';",'const validate=()=>true;');
await fs.writeFile(dir+'/cloud.mjs',code);
const values=new Map();globalThis.localStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};
globalThis.window={location:{origin:'https://example.com'}};
let response={user:{id:'user-1'}},ok=true;
globalThis.fetch=async(url,options)=>{assert.ok(url.includes('/auth/v1/signup?redirect_to='));assert.equal(JSON.parse(options.body).email,'writer@example.com');return {ok,json:async()=>response};};
const cloud=await import(pathToFileURL(dir+'/cloud.mjs').href);
assert.equal(await cloud.signup(' writer@example.com ','test-password'),null);assert.equal(cloud.session(),null);
response={access_token:'test-access',refresh_token:'test-refresh',expires_in:3600,user:{id:'user-1',email:'writer@example.com'}};
assert.equal((await cloud.signup('writer@example.com','test-password')).user.id,'user-1');assert.ok(cloud.session().expires_at>Date.now()/1000);
ok=false;response={msg:'Signups not allowed for this instance'};
await assert.rejects(cloud.signup('writer@example.com','test-password'),/Signups not allowed/);
await fs.rm(dir,{recursive:true});console.log('PASS: signup confirmation-required, immediate-session, and rejected signup responses');
