import {pathToFileURL} from 'node:url';
import 'fake-indexeddb/auto';
import assert from 'node:assert/strict';
import ts from 'typescript';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'scene-test-'));
for(const name of ['manuscript','storage']){const source=await fs.readFile('lib/'+name+'.ts','utf8');const code=ts.transpile(source,{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}).replace("'./manuscript'","'./manuscript.mjs'");await fs.writeFile(dir+'/'+name+'.mjs',code);}
const m=await import(pathToFileURL(dir+'/manuscript.mjs').href),s=await import(pathToFileURL(dir+'/storage.mjs').href);
const w=m.fresh();let e=await s.write(w,0);assert.equal(e.rev,1);assert.deepEqual((await s.read()).data,w);
const updated=structuredClone(w);updated.projects[0].scenes[0].body='안녕하세요.\n오프라인 한글 원고입니다.';
e=await s.write(updated,e.rev);assert.equal((await s.read()).data.projects[0].scenes[0].body,updated.projects[0].scenes[0].body);
await assert.rejects(s.write(w,1),/다른 탭/);assert.deepEqual((await s.read()).data,updated);assert.equal((await s.recoveries()).length,1);
await s.write(updated,e.rev,{cloudRev:7,dirty:false,owner:'owner'});assert.equal((await s.read()).cloudRev,7);assert.equal((await s.read()).dirty,false);
const p=m.sample(),moved=m.moveScene(p,p.scenes[0].id,p.scenes[3].id);assert.equal(moved.scenes[3].id,p.scenes[0].id);assert.equal(p.scenes[0].title,'문이 열리던 날');
p.scenes[0].bucket='held';assert.ok(!m.manuscript(p).includes(p.scenes[0].body));assert.ok(m.validate(w));assert.ok(!m.validate({schema:1,projects:[{id:'x'}]}));
const c=m.checkpoint(updated.projects[0].scenes[0]);assert.equal(c.versions[0].body,c.body);assert.equal(m.checkpoint(c).versions.length,1);
console.log('PASS: durable reload, Korean text, stale-tab rejection, recovery preservation, sync metadata, reorder, export exclusions, backup validation, history');
await fs.rm(dir,{recursive:true});
