export type Scene = {id:string; title:string; summary:string; body:string; notes:string; pov:string; place:string; time:string; stage:string; bucket:'active'|'held'|'trash'; versions:{at:string; body:string; title:string}[]};
export type Project = {id:string; title:string; subtitle:string; scenes:Scene[]};
export type Workspace = {schema:1; projects:Project[]};
export const uid=()=>typeof crypto.randomUUID==='function'?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');
export const newScene=(title=''):Scene=>({id:uid(),title,summary:'',body:'',notes:'',pov:'',place:'',time:'',stage:'구상',bucket:'active',versions:[]});
export function fresh():Workspace{return {schema:1,projects:[{id:uid(),title:'첫 번째 이야기',subtitle:'아직 쓰이지 않은 장면들',scenes:[newScene()]}]};}
export function sample():Project {const data=[['문이 열리던 날','오래 비어 있던 옆집에서 피아노 소리가 들린다.','복도 끝에서 피아노 소리가 났다.\n\n삼 년 동안 아무도 살지 않던 집이었다. 나는 우편함에서 꺼낸 봉투를 든 채, 한동안 계단 앞에 서 있었다. 곡은 내가 아는 데까지 흘러갔다가, 언제나 같은 자리에서 멈췄다.\n\n그다음 날에도 그랬다.','나','아파트 복도','첫째 날','초고'],['수취인 없는 편지','잘못 배달된 편지 한 통. 봉투에는 나의 옛 이름이 적혀 있다.','봉투 뒷면에는 보내는 사람의 이름이 없었다.\n\n앞면의 글씨만은 낯익었다. 한때 나는 저렇게 받침을 길게 흘려 썼다. 이름을 바꾸기 전, 이 동네를 떠나기 전이었다.','나','우편함','둘째 날','초고'],['같은 곡의 다른 끝','옆집 사람을 만난다. 그는 멈춘 다음 마디를 알고 있다.','','나','옆집 문 앞','셋째 날','구상'],['닫히지 않는 문','편지를 보낸 사람과 피아노 소리의 연결이 드러난다.','','나','옆집 거실','셋째 날 밤','구상'],['다음 마디','편지를 쓰는 대신, 멈췄던 곡의 다음 마디를 연주한다.','','나','내 방','넷째 날','구상']];return {id:uid(),title:'다음 마디',subtitle:'예시 작품 · 낯선 편지와 익숙한 멜로디',scenes:data.map(([title,summary,body,pov,place,time,stage])=>({...newScene(title),summary,body,pov,place,time,stage}))};}
export function validate(v:unknown):v is Workspace {const x=v as Workspace;return !!x&&x.schema===1&&Array.isArray(x.projects)&&x.projects.length>0&&x.projects.every(p=>typeof p.id==='string'&&typeof p.title==='string'&&typeof p.subtitle==='string'&&Array.isArray(p.scenes)&&p.scenes.every(s=>['id','title','summary','body','notes','pov','place','time','stage'].every(k=>typeof (s as any)[k]==='string')&&['active','held','trash'].includes(s.bucket)&&Array.isArray(s.versions)&&s.versions.every(v=>typeof v.at==='string'&&typeof v.body==='string'&&typeof v.title==='string')))&&new Set(x.projects.map(p=>p.id)).size===x.projects.length&&x.projects.every(p=>new Set(p.scenes.map(s=>s.id)).size===p.scenes.length);}
export function checkpoint(s:Scene):Scene {if(s.versions[0]?.body===s.body&&s.versions[0]?.title===s.title)return s;return {...s,versions:[{at:new Date().toISOString(),body:s.body,title:s.title},...s.versions].slice(0,50)};}
export function moveScene(p:Project,from:string,to:string):Project {const a=p.scenes.findIndex(s=>s.id===from),b=p.scenes.findIndex(s=>s.id===to);if(a<0||b<0||a===b)return p;const scenes=[...p.scenes];scenes.splice(b,0,scenes.splice(a,1)[0]);return {...p,scenes};}
export function manuscript(p:Project,md=false){return (md?'# ':'')+p.title+'\n\n'+p.scenes.filter(s=>s.bucket==='active').map(s=>md?'## '+s.title+'\n\n'+s.body:s.body).join('\n\n'+(md?'---':'* * *')+'\n\n');}
export function download(name:string,content:Blob|string,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(content instanceof Blob?content:new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name.replace(/[\\/:*?"<>|]/g,'_');a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
