import {type Workspace,validate} from './manuscript';
export type Envelope={data:Workspace;rev:number;cloudRev:number;dirty:boolean;owner?:string;endpoint?:string};
const NAME='scene-studio-v1';
let dbPromise:Promise<IDBDatabase>|undefined;
function db(){return dbPromise??=new Promise<IDBDatabase>((res,rej)=>{const q=indexedDB.open(NAME,1);q.onupgradeneeded=()=>{q.result.createObjectStore('state');q.result.createObjectStore('recovery',{autoIncrement:true});};q.onsuccess=()=>res(q.result);q.onerror=()=>{dbPromise=undefined;rej(q.error);};});}
export async function read():Promise<Envelope|undefined>{const d=await db();return new Promise((res,rej)=>{const tx=d.transaction('state','readonly'),q=tx.objectStore('state').get('main');q.onsuccess=()=>{if(q.result&&!validate(q.result.data))return rej(new Error('저장된 원고를 읽을 수 없습니다. 백업으로 복원해 주세요.'));res(q.result);};q.onerror=()=>rej(q.error);});}
export async function write(data:Workspace,expected:number,metadata?:Partial<Envelope>):Promise<Envelope>{const d=await db();return new Promise((res,rej)=>{const tx=d.transaction(['state','recovery'],'readwrite');let result:Envelope;let problem:Error|undefined;const store=tx.objectStore('state'),q=store.get('main');q.onsuccess=()=>{const old=q.result as Envelope|undefined;if((old?.rev??0)!==expected){problem=new Error('다른 탭에서 원고가 변경되었습니다. 현재 내용은 복구 사본으로 보존했습니다.');tx.objectStore('recovery').add({data,at:Date.now()});return;}result={cloudRev:0,...old,data,rev:expected+1,dirty:true,...metadata};store.put(result,'main');};tx.oncomplete=()=>problem?rej(problem):res(result);tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error??new Error('기기 저장 실패'));});}
export async function recoveries():Promise<{data:Workspace;at:number}[]>{const d=await db();return new Promise((res,rej)=>{const q=d.transaction('recovery').objectStore('recovery').getAll();q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error);});}
export async function preserve(data:Workspace){const d=await db();return new Promise<void>((res,rej)=>{const tx=d.transaction('recovery','readwrite');tx.objectStore('recovery').add({data,at:Date.now()});tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error);});}
