'use client';
import {useState} from 'react';
import {Plus,BookOpen,Check,Trash2,FileText,Download} from 'lucide-react';
import {type Workspace,type Project,type Scene,download} from '@/lib/manuscript';
import {count,time} from '@/lib/format';
import * as disk from '@/lib/storage';
import * as cloud from '@/lib/cloud';
import {moveBefore,moveToEnd} from '@/lib/scene-ops';

export function AccountBody({account,busy,setBusy,setAccount,setStatus}:{account:string;busy:boolean;setBusy:(v:boolean)=>void;setAccount:(v:string)=>void;setStatus:(v:string)=>void}){const [authMode,setAuthMode]=useState<'login'|'signup'>('login'),[confirmPassword,setConfirmPassword]=useState(''),[authError,setAuthError]=useState(''),[authMessage,setAuthMessage]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''); return <><h3>계정</h3><p className="muted small">{account?account:'연결 전에는 이 브라우저에만 저장됩니다.'}</p>{!account?<form className="auth-form" onSubmit={async e=>{e.preventDefault();if(busy)return;setAuthError('');setAuthMessage('');if(authMode==='signup'&&password!==confirmPassword){setAuthError('비밀번호가 일치하지 않아요.');return;}setBusy(true);try{if(authMode==='signup'){const result=await cloud.signup(email,password);setPassword('');setConfirmPassword('');if(result){setAccount(result.user.email??email);setAuthMessage('가입되었습니다.');}else{setAuthMode('login');setAuthMessage('이메일에서 인증을 완료한 뒤 로그인해 주세요. 이미 가입했다면 기존 비밀번호로 로그인하세요.');}}else{const result=await cloud.login(email.trim(),password);setAccount(result.user.email??email);setPassword('');setAuthMessage('로그인되었습니다.');}}catch(e){const message=(e as Error).message;setAuthError(message.includes('Invalid login credentials')?'이메일 또는 비밀번호를 확인해 주세요.':message.includes('Email not confirmed')?'이메일 인증을 먼저 완료해 주세요.':message.includes('Signups not allowed')?'현재 회원가입이 닫혀 있어요.':message);}finally{setBusy(false);}}}><h3>{authMode==='signup'?'회원가입':'로그인'}</h3><label>이메일<input type="email" required autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>비밀번호<input type="password" required minLength={authMode==='signup'?8:1} placeholder={authMode==='signup'?'8자 이상':''} autoComplete={authMode==='signup'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>{authMode==='signup'&&<label>비밀번호 확인<input type="password" required minLength={8} autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label>}{authError&&<p className="auth-error" role="alert">{authError}</p>}{authMessage&&<p className="auth-message" role="status">{authMessage}</p>}<button type="submit" className="primary" disabled={busy}>{busy?'처리 중…':authMode==='signup'?'가입하기':'로그인'}</button><button type="button" className="auth-switch" disabled={busy} onClick={()=>{setAuthMode(authMode==='login'?'signup':'login');setAuthError('');setAuthMessage('');setPassword('');setConfirmPassword('');}}>{authMode==='login'?'회원가입':'로그인으로 돌아가기'}</button></form>:<div className="button-row"><button className="small-button" disabled={busy} onClick={()=>{localStorage.removeItem('scene-session');setAccount('');setStatus('기기에 저장됨 · 로그아웃');}}>로그아웃</button></div>}</>;}

export function ExportBody({exportFile,importInput,recovery,setRecovery,setNotice}:{exportFile:(type:string)=>void;importInput:React.RefObject<HTMLInputElement|null>;recovery:{data:Workspace;at:number}[];setRecovery:(v:{data:Workspace;at:number}[])=>void;setNotice:(v:string)=>void}){ return <><div className="export-grid">{[['docx','Word','.docx'],['md','Markdown','.md · Notion 가져오기'],['txt','텍스트','.txt'],['json','전체 백업','.json · 메모와 저장 이력 포함']].map(([type,label,sub])=><button key={type} onClick={()=>exportFile(type)}><FileText size={22}/><strong>{label}</strong><small>{sub}</small><Download size={15}/></button>)}</div><div className="dialog-rule"/><button className="small-button" onClick={()=>importInput.current?.click()}>백업 / Markdown / TXT 가져오기</button><p className="muted small">가져온 파일은 기존 원고를 덮어쓰지 않고 새 작품으로 추가합니다.</p><div className="dialog-rule"/><button className="small-button" onClick={async()=>{const r=await disk.recoveries();setRecovery(r);if(!r.length)setNotice('복구 사본이 없어요.');}}>기기 복구 사본 확인</button>{recovery.map((r,i)=><button key={i} className="small-button" onClick={()=>download('복구-'+r.at+'.json',JSON.stringify(r.data),'application/json')}>{new Date(r.at).toLocaleString('ko-KR')} 백업 다운로드</button>)}</>;}

export function ProjectsBody({project,data,editProject,openProject,setDeleteProjectId,newProject}:{project:Project;data:Workspace;editProject:(fn:(p:Project)=>Project)=>void;openProject:(id:string)=>void;setDeleteProjectId:(v:string)=>void;newProject:(example?:boolean)=>void}){ return <><label>작품 제목<input value={project.title} onChange={e=>editProject(p=>({...p,title:e.target.value}))}/></label><label>소제목<input value={project.subtitle} placeholder="선택 사항" onChange={e=>editProject(p=>({...p,subtitle:e.target.value}))}/></label><div className="project-list">{data.projects.map(p=><div className="project-row" key={p.id}><button className="project-select" onClick={()=>openProject(p.id)}><BookOpen size={19}/><span><strong>{p.title}</strong><small>{p.scenes.filter(s=>s.bucket==='active').length} 씬</small></span>{project.id===p.id&&<Check size={17}/>}</button><button className="project-delete" aria-label={(p.title||'제목 없는 이야기')+' 작품 삭제'} title="작품 삭제" onClick={()=>setDeleteProjectId(p.id)}><Trash2 size={18}/></button></div>)}</div><div className="button-row"><button className="primary" onClick={()=>newProject()}><Plus size={16}/>새 작품</button><button className="small-button" onClick={()=>newProject(true)}>예시 작품</button></div></>;}

export function HistoryBody({scene,editScene,setDialog,setNotice}:{scene:Scene;editScene:(patch:Partial<Scene>,checkpointNow?:boolean)=>void;setDialog:(v:string)=>void;setNotice:(v:string)=>void}){ return <div className="history-list">{scene.versions.length===0?<p className="muted">본문을 수정하면 이전 내용이 여기에 남아요.</p>:scene.versions.map((v,i)=><div key={i}><strong>{time(v.at)}</strong><small>{count(v.body)}자</small><pre>{v.body||'(빈 본문)'}</pre><button className="small-button" onClick={()=>{editScene({body:v.body,title:v.title},true);setDialog('');setNotice('이전 내용으로 복원했어요. 복원 전 원고도 이력에 남겼어요.');}}>이 버전 복원</button></div>)}</div>;}

export function ConflictBody({conflict,data,busy,useServerManuscript,resolveConflict}:{conflict:{payload:Workspace;revision:number};data:Workspace;busy:boolean;useServerManuscript:()=>void;resolveConflict:()=>void}){ return <><p className="small muted">서버 원고를 선택하면 이 기기의 작품 목록 전체가 서버 원고로 바뀝니다. 중복 작품은 만들지 않으며, 기존 기기 원고는 내보내기의 복구 사본에 남습니다.</p><button className="primary" disabled={busy} onClick={()=>void useServerManuscript()}>{busy?'처리 중…':'서버 원고로 이 기기 교체'}</button><div className="dialog-rule"/><p className="small muted">양쪽에서 작업했다면 기기 작품 {data.projects.length}개와 서버 작품 {conflict.payload.projects.length}개를 각각 보존할 수 있어요.</p><button className="small-button" disabled={busy} onClick={()=>void resolveConflict()}>두 버전 모두 보존하고 계속</button><button className="small-button" disabled={busy} onClick={()=>download('서버-원고-백업.json',JSON.stringify(conflict.payload),'application/json')}>서버 원고 백업 받기</button></>;}

// 목록에서 고른 씬 앞으로 옮긴다. 목차와 같은 모양을 쓴다.
export function MoveBody({project,scene,setUndo,editProject,setDialog}:{project:Project;scene:Scene;setUndo:(v:string[]|null)=>void;editProject:(fn:(p:Project)=>Project)=>void;setDialog:(v:string)=>void}){
 const list=project.scenes.filter(s=>s.bucket===scene.bucket),move=(fn:(p:Project)=>Project)=>{setUndo(project.scenes.map(x=>x.id));editProject(fn);setDialog('');};
 const last=list[list.length-1];
 return <nav className="outline-list" aria-label="옮길 위치">{list.map((s,i)=>s.id===scene.id?<button key={s.id} aria-current="true" disabled><span>{String(i+1).padStart(2,'0')}</span><strong>{s.title||'제목 없는 씬'}</strong><span className="move-hint">지금 위치</span></button>:<button key={s.id} onClick={()=>move(p=>moveBefore(p,scene.id,s.id))}><span>{String(i+1).padStart(2,'0')}</span><strong>{s.title||'제목 없는 씬'}</strong><span className="move-hint">이 앞으로</span></button>)}{last&&last.id!==scene.id&&<button onClick={()=>move(p=>moveToEnd(p,scene.id))}><span/><strong>맨 끝으로</strong><span/></button>}</nav>;
}
